<?php
/**
 * ExpertsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Elev8er\PublicApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * elev8er Public API
 *
 * Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@elev8er.ai
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Elev8er\PublicApi\Test\Api;

use \Elev8er\PublicApi\Configuration;
use \Elev8er\PublicApi\ApiException;
use \Elev8er\PublicApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ExpertsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Elev8er\PublicApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExpertsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createAvailability
     *
     * Create an availability entry.
     *
     */
    public function testCreateAvailability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createExpert
     *
     * Create an expert.
     *
     */
    public function testCreateExpert()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createSession
     *
     * Create a session.
     *
     */
    public function testCreateSession()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAvailability
     *
     * Delete an availability entry.
     *
     */
    public function testDeleteAvailability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteExpert
     *
     * Delete an expert.
     *
     */
    public function testDeleteExpert()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSession
     *
     * Delete a session.
     *
     */
    public function testDeleteSession()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAvailability
     *
     * Get an availability entry.
     *
     */
    public function testGetAvailability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getExpert
     *
     * Get an expert by id.
     *
     */
    public function testGetExpert()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getExpertAvailability
     *
     * Get an expert's availability.
     *
     */
    public function testGetExpertAvailability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSession
     *
     * Get a session.
     *
     */
    public function testGetSession()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listExpertSessions
     *
     * List sessions for an expert.
     *
     */
    public function testListExpertSessions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listExperts
     *
     * List experts.
     *
     */
    public function testListExperts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSessions
     *
     * List sessions.
     *
     */
    public function testListSessions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setExpertAvailability
     *
     * Replace an expert's availability.
     *
     */
    public function testSetExpertAvailability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAvailability
     *
     * Update an availability entry.
     *
     */
    public function testUpdateAvailability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateExpert
     *
     * Update an expert.
     *
     */
    public function testUpdateExpert()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSession
     *
     * Update a session.
     *
     */
    public function testUpdateSession()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSessionStatus
     *
     * Update a session's status.
     *
     */
    public function testUpdateSessionStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
