<?php
/**
 * ProgramsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Elev8er\PublicApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * elev8er Public API
 *
 * Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@elev8er.ai
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Elev8er\PublicApi\Test\Api;

use \Elev8er\PublicApi\Configuration;
use \Elev8er\PublicApi\ApiException;
use \Elev8er\PublicApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProgramsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Elev8er\PublicApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProgramsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createProgram
     *
     * Create a program.
     *
     */
    public function testCreateProgram()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createProgramTag
     *
     * Create a program tag.
     *
     */
    public function testCreateProgramTag()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createProgramVersion
     *
     * Create a new version of a program.
     *
     */
    public function testCreateProgramVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteProgram
     *
     * Delete a program.
     *
     */
    public function testDeleteProgram()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteProgramTag
     *
     * Delete a program tag.
     *
     */
    public function testDeleteProgramTag()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProgram
     *
     * Get a program by id.
     *
     */
    public function testGetProgram()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProgramTags
     *
     * Get tags assigned to a program.
     *
     */
    public function testGetProgramTags()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProgramVersion
     *
     * Get a specific program version.
     *
     */
    public function testGetProgramVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listProgramTags
     *
     * List program tags.
     *
     */
    public function testListProgramTags()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listProgramVersions
     *
     * List versions of a program.
     *
     */
    public function testListProgramVersions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPrograms
     *
     * List programs.
     *
     */
    public function testListPrograms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rollbackProgramVersion
     *
     * Roll a program back to a specific version.
     *
     */
    public function testRollbackProgramVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setProgramTags
     *
     * Replace the tags assigned to a program.
     *
     */
    public function testSetProgramTags()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateProgram
     *
     * Update a program.
     *
     */
    public function testUpdateProgram()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateProgramTag
     *
     * Update a program tag.
     *
     */
    public function testUpdateProgramTag()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateProgramVersion
     *
     * Update a specific program version.
     *
     */
    public function testUpdateProgramVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
