<?php
/**
 * TestsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Elev8er\PublicApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * elev8er Public API
 *
 * Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@elev8er.ai
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Elev8er\PublicApi\Test\Api;

use \Elev8er\PublicApi\Configuration;
use \Elev8er\PublicApi\ApiException;
use \Elev8er\PublicApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TestsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Elev8er\PublicApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TestsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createTest
     *
     * Create a test.
     *
     */
    public function testCreateTest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createTestVersion
     *
     * Create a new version of a test.
     *
     */
    public function testCreateTestVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteTest
     *
     * Delete a test.
     *
     */
    public function testDeleteTest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTest
     *
     * Get a test by id.
     *
     */
    public function testGetTest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTestVersion
     *
     * Get a specific test version.
     *
     */
    public function testGetTestVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listTestVersions
     *
     * List versions of a test.
     *
     */
    public function testListTestVersions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listTests
     *
     * List tests.
     *
     */
    public function testListTests()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rollbackTestVersion
     *
     * Roll a test back to a specific version.
     *
     */
    public function testRollbackTestVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateTest
     *
     * Update a test.
     *
     */
    public function testUpdateTest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateTestVersion
     *
     * Update a specific test version.
     *
     */
    public function testUpdateTestVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
